# Generated by Django 3.2.4 on 2021-06-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap_server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='assembled',
            field=models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=False, null=True, verbose_name='В сборке'),
        ),
    ]
