# Generated by Django 3.2.4 on 2021-07-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap_server', '0004_alter_certification_assembled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings1560',
            name='filter_index',
            field=models.IntegerField(choices=[(0, '10 kHz'), (1, '20 kHz'), (2, '40 kHz'), (3, 'BYPASS')], default=None, verbose_name='Фильтр'),
        ),
    ]
