# Generated by Django 3.2.4 on 2021-09-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap_server', '0006_model_model_postfix'),
    ]

    operations = [
        migrations.AddField(
            model_name='operators',
            name='courses',
            field=models.ManyToManyField(to='cap_server.Controllers'),
        ),
    ]
