# Generated by Django 3.2.4 on 2021-09-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap_server', '0009_operators_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='capacity_line',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='Канал емкости'),
        ),
        migrations.AddField(
            model_name='base',
            name='zonder_line',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='Канал зондера'),
        ),
    ]
