# Generated by Django 3.2.4 on 2021-09-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap_server', '0012_auto_20210921_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings1560',
            name='tvg_K2',
            field=models.BooleanField(choices=[(True, 'on'), (False, 'off')], default=False, verbose_name='2 каскад'),
        ),
    ]
