# Generated by Django 3.2.4 on 2021-09-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap_server', '0013_settings1560_tvg_k2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings1560',
            name='accumulation',
            field=models.PositiveIntegerField(verbose_name='Накопление'),
        ),
    ]
