# Generated by Django 3.2.4 on 2021-09-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap_server', '0015_operators_verification_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controllers',
            name='status',
            field=models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=None, verbose_name='Администратор'),
        ),
        migrations.AlterField(
            model_name='operators',
            name='status',
            field=models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=None, verbose_name='Администратор'),
        ),
    ]
