# Generated by Django 3.2.8 on 2021-10-13 06:26

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelPEP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=10, unique=True, verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Модели ПЭП',
                'verbose_name_plural': 'Модели ПЭП',
                'db_table': 'pep_model',
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
