# Generated by Django 3.2.8 on 2021-10-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pep_server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectPEP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect', models.CharField(default=None, max_length=50)),
            ],
            options={
                'verbose_name': 'Модели ПЭП',
                'verbose_name_plural': 'Модели ПЭП',
                'db_table': 'pep_defect',
            },
        ),
    ]
