# Generated by Django 3.2.8 on 2021-10-13 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pep_server', '0002_defectpep'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defectpep',
            options={'verbose_name': 'Дефекты ПЭП', 'verbose_name_plural': 'Дефекты ПЭП'},
        ),
    ]
