# Generated by Django 3.2.8 on 2021-10-18 13:10

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('pep_server', '0003_alter_defectpep_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasePEP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postfix', models.CharField(max_length=15, unique=True, verbose_name='Постфикс')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pep_server.modelpep', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Базовые х-ки ПЭП',
                'verbose_name_plural': 'Базовые х-ки ПЭП',
                'db_table': 'pep_base',
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
