# Generated by Django 3.2.8 on 2021-11-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AAAData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addload', models.IntegerField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'data',
            },
        ),
    ]
