# Generated by Django 3.2.8 on 2021-11-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomography_ann', '0002_auto_20211126_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aaadata',
            old_name='data',
            new_name='bcd',
        ),
        migrations.AddField(
            model_name='aaadata',
            name='alimax',
            field=models.IntegerField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='aaadata',
            name='alimin',
            field=models.IntegerField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='aaadata',
            name='amaxC',
            field=models.IntegerField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='aaadata',
            name='amaxD',
            field=models.IntegerField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='aaadata',
            name='balance',
            field=models.IntegerField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='aaadata',
            name='bcdl',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='aaadata',
            name='bcdr',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='aaadata',
            name='bscan',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='aaadata',
            name='cscan',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='aaadata',
            name='dxn',
            field=models.IntegerField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='aaadata',
            name='dydsize',
            field=models.IntegerField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='aaadata',
            name='idxDualAR',
            field=models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=False, null=True),
        ),
        migrations.AddField(
            model_name='aaadata',
            name='idxSingleARposition',
            field=models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=False, null=True),
        ),
        migrations.AddField(
            model_name='aaadata',
            name='levelfix',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='aaadata',
            name='poroglvl',
            field=models.IntegerField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='aaadata',
            name='stpY',
            field=models.IntegerField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='aaadata',
            name='wa',
            field=models.IntegerField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='aaadata',
            name='weldparam',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='aaadata',
            name='xm',
            field=models.IntegerField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='aaadata',
            name='ym',
            field=models.IntegerField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='aaadata',
            name='zm',
            field=models.IntegerField(max_length=1024, null=True),
        ),
        migrations.AlterModelTable(
            name='aaadata',
            table='aaa_data',
        ),
    ]
