# Generated by Django 3.2.8 on 2021-11-30 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tomography_ann', '0004_auto_20211130_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aaadata',
            name='dxn',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='XYZData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(null=True)),
                ('y', models.IntegerField(null=True)),
                ('z', models.IntegerField(null=True)),
                ('dx', models.IntegerField(null=True)),
                ('dy', models.IntegerField(null=True)),
                ('dz', models.IntegerField(null=True)),
                ('a', models.IntegerField(null=True)),
                ('da', models.IntegerField(null=True)),
                ('result', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tomography_ann.aaadata')),
            ],
            options={
                'verbose_name': 'Дефект',
                'verbose_name_plural': 'Дефекты',
                'db_table': 'xyz_data',
            },
        ),
    ]
