# Generated by Django 3.2.8 on 2021-11-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomography_ann', '0005_auto_20211130_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='xyzdata',
            name='typy_defect',
            field=models.IntegerField(choices=[(0, 'Плоскостной'), (1, 'Объемный'), (3, 'Объемно-плоскостной')], default=None, verbose_name='Дефект'),
        ),
    ]
