# Generated by Django 3.2.8 on 2021-11-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tomography_ann', '0006_xyzdata_typy_defect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aaadata',
            name='alimax',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aaadata',
            name='alimin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aaadata',
            name='amaxC',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aaadata',
            name='amaxD',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aaadata',
            name='balance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aaadata',
            name='bcd',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aaadata',
            name='bcdl',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aaadata',
            name='bcdr',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aaadata',
            name='bscan',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aaadata',
            name='cscan',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aaadata',
            name='dxn',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aaadata',
            name='dydsize',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aaadata',
            name='idxDualAR',
            field=models.BooleanField(blank=True, choices=[(True, 'Да'), (False, 'Нет')], default=False, null=True),
        ),
        migrations.AlterField(
            model_name='aaadata',
            name='idxSingleARposition',
            field=models.BooleanField(blank=True, choices=[(True, 'Да'), (False, 'Нет')], default=False, null=True),
        ),
        migrations.AlterField(
            model_name='aaadata',
            name='levelfix',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='aaadata',
            name='poroglvl',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aaadata',
            name='stpY',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aaadata',
            name='wa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aaadata',
            name='weldparam',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aaadata',
            name='xm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aaadata',
            name='ym',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aaadata',
            name='zm',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
